# Generated by Django 3.1.3 on 2020-11-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=60)),
                ('cover', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('reading_status', models.CharField(choices=[('READ', 'Read'), ('TO_READ', 'To Read'), ('READING', 'Reading')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('books', models.ManyToManyField(to='books_server.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='bookshelves',
            field=models.ManyToManyField(to='books_server.Bookshelf'),
        ),
    ]
