# Generated by Django 3.1.3 on 2020-11-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='books',
        ),
    ]
