# Generated by Django 3.1.3 on 2020-11-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_server', '0003_auto_20201115_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='book',
            new_name='books',
        ),
    ]
