# Generated by Django 3.1.3 on 2020-11-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_server', '0004_auto_20201115_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='bookshelf',
            field=models.ManyToManyField(to='books_server.Bookshelf'),
        ),
    ]
