# Generated by Django 3.1.3 on 2020-11-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_server', '0005_auto_20201115_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookshelf',
            new_name='bookshelves',
        ),
    ]
