# Generated by Django 3.1.3 on 2020-11-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_server', '0007_auto_20201116_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookshelves',
            new_name='bookshelf',
        ),
    ]
