# Generated by Django 3.1.3 on 2020-11-18 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_server', '0009_auto_20201118_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
