# Generated by Django 3.1.3 on 2020-11-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_server', '0011_bookshelf_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
    ]
